name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

jobs:
  build:
      strategy:
        matrix:
          os: [windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v1

        - name: Install Node.js, NPM and Yarn
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: Install deps
          run: |
            npm run install-deps

        - name: Build/release Electron app
          uses: samuelmeuli/action-electron-builder@v1
          with:
            # GitHub token, automatically provided to the action
            # (No need to define this secret in the repo settings)
            github_token: ${{ secrets.github_token }}
            # If the commit is tagged with a version (e.g. "v1.0.0"),
            # release the app after building
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}
            mac_certs: ${{ secrets.mac_certs }}
            mac_certs_password: ${{ secrets.mac_certs_password }}

        - name: Upload build result to artifact
          if: steps.build.outputs.fail == '1'
          uses: actions/upload-artifact@v2
          with:
            name: target-${{ runner.OS }}
            path:
              - dist/*.dmg
              - dist/*.exe
        - name: Fail after upload build result
          if: steps.build.outputs.fail == '1'
          run: "false"

