name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

jobs:
  build:
      strategy:
        matrix:
          os: [windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v1

        - name: Install Node.js, NPM and Yarn
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: Install deps
          run: |
            npm run install-deps

        - name: build windows app
          if: matrix.os == 'windows-latest'
          run: |
            npm run dist:win
          env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        - name: build mac app
          if: matrix.os == 'macos-latest'
          run: |
            npm run dist:mac
          env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        - name: upload windows app
          if: matrix.os == 'windows-latest'
          uses: actions/upload-artifact@v2
          with:
            name: target-${{ runner.OS }}
            path: release/*.exe

        - name: upload mac app
          if: matrix.os == 'mac-latest'
          uses: actions/upload-artifact@v2
          with:
            name: target-${{ runner.OS }}
            path: release/*.dmg
